[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sarpyx"
version = "0.1.0"
description = "A swissknife for SAR processing."
authors = [
    { name = "Roberto Del Prete", email = "roberto.delprete@esa.int" }
]
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "matplotlib",
    "lxml", 
    "scipy",
    "geopandas",
    "shapely",
    "numpy",
    "openpyxl",
    "h5py",
    "numba",
    "jupyter",
    "torch>=1.9.0",
    "pandas",
    "gdal"
]

[tool.setuptools]
packages = ["sarpyx"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.json", "*.xml"]