[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sarpyx"
version = "0.1.0"
description = "A swissknife for SAR processing."
authors = [
    { name = "Roberto Del Prete", email = "roberto.delprete@esa.int" }
]
license = { text = "MIT" }
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "lxml", 
    "scipy",
    "s1isp @ git+https://github.com/avalentino/s1isp.git",
    "geopandas",
    "shapely",
    "numpy",
    "openpyxl",
    "h5py",
    "numba",
    "jupyter",
    "torch>=1.9.0",
    "pandas",
    "phidown>=0.1.12",
    "rasterio>=1.4.3",
    "zarr>=3.0.8",
    "joblib>=1.5.1",
]

[tool.setuptools]
packages = ["sarpyx"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.json", "*.xml"]